#+TITLE: Breakpoint model
#+Author: 

* Subject specific, single breakpoint, single slope

** Direct optimisation

Consider a response variable \(Y\) and an explanatory variable \(X\)
related by:
#+BEGIN_EXPORT latex
\begin{align*}
Y = \beta X - \beta (X - \psi)_+ + \varepsilon
\end{align*}
#+END_EXPORT

\noindent where \((\beta,\psi) \in \Real^2\), \(\varepsilon
\sim \Gaus[0,\sigma^2]\), and \((x)_+=x\) if \(x>0\) and 0
otherwise. Introduce \(\Theta = (\beta,\psi,\sigma^2)\), we can
express the likelihood relative to \(n\) iid observations as:
#+BEGIN_EXPORT latex
\begin{align*}
\Likelihood(\Theta) = \prod_{i=1}^n \frac{1}{\sqrt{2\pi\sigma^2}}\exp\left(-\frac{(Y_i - \beta X_i + \beta (X_i - \psi)_+)^2}{2\sigma^2}\right)
\end{align*}
#+END_EXPORT
and the log-likelihood as:
#+BEGIN_EXPORT latex
\begin{align*}
\likelihood(\Theta) = - \frac{n}{2} \log(2\pi) - \frac{n}{2} \log(\sigma^2) - \sum_{i=1}^n \frac{\left(Y_i - \beta X_i + \beta (X_i - \psi)_+\right)^2}{2\sigma^2}
\end{align*}
#+END_EXPORT

\noindent Maximizing the likelihood with respect to \(\Theta_\mu =
(\beta,\psi)\) is equivalent to minimizing the residual sum of
squared (RSS):
#+BEGIN_EXPORT latex
\begin{align*}
RSS(\Theta_\mu) = \sum_{i=1}^n (Y_i - \beta X_i + \beta (X_i - \psi)_+)^2
\end{align*}
#+END_EXPORT

One approach to estimate the model parameters is to directly minimize
this log-likelihood using, for instance grid search. This may be
numerically inefficient but does not require any smoothness assumption
on the likelihood.
- this is what =optim.lmbreak_NLMINB= in the lmbreak package does (set
  argument =control= to =list(optimizer = "nlminb")=). =nlminb= seems
  to employ a quasi Newton method though, some does require some
  smoothness.

\clearpage

** Gradient descent

One can re-write the residual sum of squares as:
#+BEGIN_EXPORT latex
\begin{align*}
RSS(\Theta_\mu) = \sum_{i=1}^n \varepsilon_i(\psi)^2  = Y (I-H(\psi))\trans{(I-H(\psi))}\trans{Y} = Y (I-H(\psi))\trans{Y}
\end{align*}
#+END_EXPORT
where \(H(\psi) =
Z(\psi)\left(\trans{Z}(\psi)Z(\psi)\right)^{-1}\trans{Z}(\psi)\) is
the hat matrix and \({Z(\psi)=(X-(X-\psi)_+)}\). It is idempotent and so is \(I-H\) where \(I\) denote
the identity matrix. Therefore a possible derivative w.r.t. \(\psi\) of the RSS is:
#+BEGIN_EXPORT latex
\begin{align*}
\frac{\partial RSS(\Theta_\mu)}{\partial \psi} =& - Y \frac{\partial H(\psi)}{\partial \psi} \trans{Y} \\
 =& - Y \frac{\partial Z(\psi)}{\partial \psi} \left(\trans{Z}(\psi) Z(\psi)\right)^{-1}\trans{Z}(\psi) \trans{Y} \\
  & + Y Z(\psi) \left(\trans{Z}(\psi) Z(\psi)\right)^{-1} \left(\frac{\partial \trans{Z}(\psi)}{\partial \psi}Z(\psi)+\trans{Z}(\psi)\frac{\partial Z(\psi)}{\partial \psi} \right) \left(\trans{Z}(\psi) Z(\psi)\right)^{-1}\trans{Z}(\psi) \trans{Y} \\
  &  - Y Z(\psi) \left(\trans{Z}(\psi)  Z(\psi)\right)^{-1} \frac{\partial \trans{Z}(\psi)}{\partial \psi} \trans{Y}
\end{align*}
#+END_EXPORT
The first and last term being scalar and transpose of each other they
are equal. Similarly the two middle terms are also scalar and
transpose of each other so equal. Therefore:
#+BEGIN_EXPORT latex
\begin{align*}
\frac{\partial RSS(\Theta_\mu)}{\partial \psi}
=& - 2 Y \frac{\partial Z(\psi)}{\partial \psi} \left(\trans{Z}(\psi) Z(\psi)\right)^{-1}\trans{Z}(\psi) \trans{Y} \\
 & + 2 Y Z(\psi) \left(\trans{Z}(\psi) Z(\psi)\right)^{-1} \left(\trans{Z}(\psi)\frac{\partial Z(\psi)}{\partial \psi} \right) \left(\trans{Z}(\psi) Z(\psi)\right)^{-1}\trans{Z}(\psi) \trans{Y} \\
=& 2 Y \left(- \frac{\partial Z(\psi)}{\partial \psi} + Z(\psi) \left(\trans{Z}(\psi) Z(\psi)\right)^{-1} \trans{Z}(\psi)\frac{\partial Z(\psi)}{\partial \psi} \right) \left(\trans{Z}(\psi) Z(\psi)\right)^{-1}\trans{Z}(\psi) \trans{Y} \\
=& 2 Y \left(Z(\psi) \left(\trans{Z}(\psi) Z(\psi)\right)^{-1} \trans{Z}(\psi) - I \right) \frac{\partial Z(\psi)}{\partial \psi} \left(\trans{Z}(\psi) Z(\psi)\right)^{-1}\trans{Z}(\psi) \trans{Y}
\end{align*}
#+END_EXPORT
So it only remains to evaluate the (sub-)derivatives of \(X(\psi)\):
#+BEGIN_EXPORT latex
\begin{align*}
\frac{\partial Z(\psi)}{\partial \psi} = \frac{\partial (X-\psi)\Ind[X>\psi]}{\partial \psi}
 = -\Ind[X>\psi] - \Ind[X=\psi]\delta = -(\Ind[X>\psi] +\Ind[X=\psi]\delta) 
\end{align*}
#+END_EXPORT
where \(\delta \in [0,1]\).

\bigskip

So a second approach to estimate the model parameters is to perform a
gradient descent based on sub-derivatives
- this is what =optim.lmbreak_BFGS= in the lmbreak package does (set
  argument =control= to =list(optimizer = "BFGS")=). \(\delta\) is then randomly
  sampled in a uniform distribution whose support is \([0,1]\).

\clearpage


\noindent *Note*: another approach to 'profile-out' the \(\beta\), is to first
 plug-in the OLS estimator:
#+BEGIN_EXPORT latex
\begin{align*}
\tilde{\beta}(\psi) &= \frac{\sum_{i=1}^n X_i Y_i - (X_i - \psi)_+ Y_i}{\sum_{i=1}^n (X_i + (X_i - \psi)_+)^2} = \frac{\sum_{i=1}^n \Ind[X_i \leq \psi] X_i Y_i}{\sum_{i=1}^n \Ind[X_i \leq \psi] X^2_i} 
\end{align*}
#+END_EXPORT

and then minimize w.r.t. \(\psi\):
#+BEGIN_EXPORT latex
\begin{align*}
\likelihood(\psi) &= \sum_{i=1}^n (Y_i - \tilde{\beta}(\psi) X_i + \tilde{\beta}(\psi) (X_i - \psi)_+)^2
\end{align*}
#+END_EXPORT

So the first 'derivative' should solve:
#+BEGIN_EXPORT latex
\begin{align*}
0 =& -2 \sum_{i=1}^n \left[
  \frac{\partial \tilde{\beta}(\psi)}{\partial \psi} (X_i - (X_i - \psi)_+)
- \tilde{\beta}(\psi)\frac{\partial (X_i - \psi)_+}{\partial \psi}\right]
(Y_i - \tilde{\beta}(\psi) X_i + \tilde{\beta}(\psi)(X_i - \psi)_+ ) \\
0 =& \frac{\partial \tilde{\beta}(\psi)}{\partial \psi} \sum_{i=1}^n (X_i - (X_i - \psi)_+)(Y_i - \tilde{\beta}(\psi) X_i + \tilde{\beta}(\psi)(X_i - \psi)_+ ) \\
& - \tilde{\beta}(\psi)\sum_{i=1}^n\frac{\partial (X_i - \psi)_+}{\partial \psi}(Y_i - \tilde{\beta}(\psi) X_i + \tilde{\beta}(\psi)(X_i - \psi)_+ ) 
\end{align*}
#+END_EXPORT
Noticing that \(\tilde{\beta}(\psi)\) is a step function with jumps at
\((X_i)_{i\in\{1,\ldots,n\}}\). If the breakpoint does not coincide
with any datapoint, it has derivative 0 w.r.t. \(\psi\). Under such
assumption, the previous expression simplifies into:

#+BEGIN_EXPORT latex
\begin{align*}
0 =& - \tilde{\beta}(\psi)\sum_{i=1}^n \Ind[X_i \geq \psi] (Y_i - \tilde{\beta}(\psi) \psi)  \\
\frac{1}{n}\sum_{i=1}^n \Ind[X_i \geq \psi] Y_i =& \tilde{\beta}(\psi) \psi
\end{align*}
#+END_EXPORT

So the breakpoint should be such that the average post-breakpoint value equal the fitted plateau.

\clearpage

** Example

Simulate some data:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
library(lmbreak)

set.seed(10)
df10 <- simBreak(c(1, 100), breakpoint = c(0,2,4),
                 slope = c(1,0), sigma = 0.05)
#+END_SRC

Automatic fit of the breakpoint model:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
e.lmbreak10 <- lmbreak(Y ~ 0 + bp(X, pattern = "10", start = c(2)),
                       data = df10)
logLik(e.lmbreak10)
#+END_SRC

#+RESULTS:
: [1] 161.5047


Estimates:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
model.tables(e.lmbreak10)
#+END_SRC


#+RESULTS:
:            X duration intercept    slope
: 1 0.05773562 1.940347 0.0579186 1.003169
: 2 1.99808295 1.847127 2.0044152 0.000000
: 3 3.84520966       NA 2.0044146       NA

OLS:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
XX <- df10$X - pmax(df10$X-coef(e.lmbreak10),0)
solve(t(XX) %*% XX) %*% t(XX) %*% df10$Y
#+END_SRC

#+RESULTS:
: [,1]
: [1,] 1.003169

Explicit OLS:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
sum((df10$X < coef(e.lmbreak10))*df10$X*df10$Y)/sum((df10$X < coef(e.lmbreak10))*df10$X^2)
#+END_SRC

#+RESULTS:
: [1] 1.003169

\clearpage

Full likelihood:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
calcLogLik <- function(theta){
  beta <- theta["beta"]
  psi <- theta["psi"]
  sigma <- exp(theta["logsigma"])
  out <- NROW(df10)/2 * log(2*pi) + NROW(df10)/2 * log(sigma) + sum((df10$Y - beta * df10$X + beta * pmax(df10$X - psi,0))^2)/(2*sigma)
  return(unname(out))
}
## By default optim performs minimization
theta.init <- c(beta = 0, psi = 1, logsigma = 0.5)
res.opt <- optim(par = theta.init, fn = calcLogLik)
c(res.opt$par, value = res.opt$value)
#+END_SRC

#+RESULTS:
:        beta         psi    logsigma       value 
:    1.003165    1.998090   -6.067996 -161.504705

We retrieve the estimate and log-likelihood of =lmbreak=.


\clearpage

* Mixed model, single breakpoint, single slope

** Example

We will consider a dataset of 20 subjects with 25 observations each:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
library(lmbreak)
library(mvtnorm)

## data generating parameters
n.subject <- 50
sigma2T <- 0.005
betaT <- 1
psiT <- 2
MtauT <- tcrossprod(c(0.2,0.1)) * matrix(c(1,0.5,0.5,1),2,2)
seqTime <- seq(0,4,length.out=25)

set.seed(10)
RE <- rmvnorm(n.subject, mean = c(psiT,betaT), sigma = MtauT)

ls.sim <- lapply(1:n.subject, function(iS){ ## iS <- 1  
  iSim <- simBreak(c(1, length(seqTime)),
                   breakpoint = c(min(seqTime),RE[iS,1],max(seqTime)),
                   slope = c(RE[iS,2],0), sigma = sqrt(sigma2T),
                   rdist.X = seqTime)
  iSim$id <- iS
  iSim
})
df.sim <- do.call(rbind,ls.sim)
#+END_SRC

#+RESULTS:
: lmbreak version 0.1.2

#+ATTR_LaTeX: :width 1\textwidth :options trim={0 0 0 0},clip :placement [!h]
[[./figures/gg-traj-mixed.pdf]]


#+BEGIN_SRC R :exports none :results output :session *R* :cache no
library(ggplot2)
ggTraj <- ggplot(df.sim, aes(x = X, y = Y, color = as.factor(id), group = as.factor(id))) + geom_point() + geom_line()
ggsave(ggTraj + guides(color = "none"), filename = file.path("figures","gg-traj-mixed.pdf"), height = 2.5, width = 5)
#+END_SRC

#+RESULTS:

\clearpage

** Model

Consider a set of \(n\) subjects each undergoing \(T\) measurements at
equally spaced timepoints \(1,\ldots,T\) of an outcome variable
\(Y\). We consider the following random slope and random breakpoint
model:
#+BEGIN_EXPORT latex
\begin{align*}
Y_{i,t} =& \beta_i t - \beta_i (t - \psi_i)_+ + \varepsilon_{i,t}
\end{align*}
#+END_EXPORT
where \(\beta_i = \beta + u_i\) and \(\psi_i = \psi + v_i\) and:
#+BEGIN_EXPORT latex
\begin{align*}
\begin{bmatrix}
u_i    \\         
v_i    \\
\varepsilon_{i,t} \\
\end{bmatrix}
= \Gaus \left(
\begin{bmatrix}
0    \\         
0    \\
0    \\
\end{bmatrix},
\begin{bmatrix}
\tau_{u,u} & \tau_{u,v} & 0 \\         
\tau_{u,v} & \tau_{v,v} & 0 \\         
0          & 0          & \sigma^2 \\         
\end{bmatrix}
\right)
\end{align*}
#+END_EXPORT
We further denote \(\Sigma_\tau= \begin{bmatrix} \tau_{u,u} &
\tau_{u,v} \\ \tau_{u,v} & \tau_{v,v} \end{bmatrix}\) whose inverse is
\(\Sigma^{-1}_\tau = \begin{bmatrix} w_{u,u} & w_{u,v} \\ w_{u,v} &
w_{v,v} \end{bmatrix} =
\frac{1}{\tau_{u,u}\tau_{v,v}-\tau^2_{u,v}} \begin{bmatrix} \tau_{v,v}
& -\tau_{u,v} \\ -\tau_{u,v} & \tau_{u,u} \end{bmatrix}\). We now can re-write the model as:
#+BEGIN_EXPORT latex
\begin{align*}
Y_{i,t} =& \beta (t - (t - \psi - v_i)_+) + u_i (t - (t - \psi - v_i)_+) + \varepsilon_{i,t} \\
        =& \mu(t,\beta,\psi,u_i,v_i) + \varepsilon_{i,t}
\end{align*}
#+END_EXPORT
where \(\mu(t,\beta,\psi,u_i,v_i) = \beta t + u_i t \) when \(t \leq
\psi + v_i\) \newline and \(\mu(t,\beta,\psi,u_i,v_i) = \beta (\psi +
v_i) + u_i (\psi + v_i) \) otherwise.

** Likelihood
*** Bivariate integral

Introduce \(\Theta =
(\beta,\psi,\tau_{u,u},\tau_{u,v},\tau_{v,v},\sigma^2)\), we can
express the likelihood relative to \(n\) iid subjects as:
#+BEGIN_EXPORT latex
\begin{align*}
\Likelihood(\Theta) &= \prod_{i=1}^n \prod_{t=1}^T \int_{u_i=-\infty}^{+\infty}\int_{v_i=-\infty}^{+\infty} \frac{1}{\sqrt{2\pi\sigma^2}}\exp\left(-\frac{(Y_i - \mu(t,\beta,\psi,u_i,v_i))^2}{2\sigma^2}\right)f_{\tau}(u,v) dv_i du_i \\
\text{ where } f_{\tau}(u,v) =& \frac{1}{2\pi \left|\Sigma_\tau\right|^{1/2}} \exp\left(-\frac{1}{2}\begin{bmatrix}u & v \end{bmatrix}\Sigma^{-1}_\tau\begin{bmatrix}u\\ v \end{bmatrix}\right) \\
              =& \frac{1}{2\pi \sqrt{\tau_{u,u}\tau_{v,v}-\tau^2_{u,v}}} \exp\left(-\frac{u^2 w_{u,u}+2uv w_{u,v}+v^2 w_{v,v}}{2}\right)
\end{align*}
#+END_EXPORT

\clearpage

One could evaluate this log-likelihood using numerical integration but
this will typically be very slow:
- e.g. for a single subject at a single timepoint:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
system.time( ## single subject
  resIntegral2 <- logLik_mixed10(
    Y = df.sim[df.sim$id==1,"Y"], t = df.sim[df.sim$id==1,"X"],
    beta = betaT, psi = psiT, tau_uu = MtauT, sigma2 = sigma2T,
    integration = "bivariate")
)
#+END_SRC

#+RESULTS:
:   bruger   system forløbet 
:    11.64     0.61    12.30

#+BEGIN_SRC R :exports both :results output :session *R* :cache no
head(resIntegral2)
#+END_SRC

#+RESULTS:
:   integral1 error1 integral2 error2 integral        error    logLik
: 1        NA     NA        NA     NA 4.220886 4.167256e-05 1.4400450
: 2        NA     NA        NA     NA 4.810385 4.781720e-05 1.5707771
: 3        NA     NA        NA     NA 2.947878 2.925916e-05 1.0810858
: 4        NA     NA        NA     NA 3.071459 3.067560e-05 1.1221526
: 5        NA     NA        NA     NA 2.468231 2.417586e-05 0.9035015
: 6        NA     NA        NA     NA 2.181033 2.144690e-05 0.7797984

Since standard optimizers may evaluate the likelihood a large number
of times this direct approach is not really feasible (too slow).


*** Nested univariate integrals


To simplify the numerical integration for a bivariate integral to
univariate integral, we start by splitting second integral depending
on whether \(t \leq \psi + v_i\) i.e. \(v_i \geq t - \psi\):
#+BEGIN_EXPORT latex
\begin{align*}
\Likelihood(\Theta) =& \prod_{i=1}^n \prod_{t=1}^T \int_{u_i=-\infty}^{+\infty}\int_{v_i=t-\psi}^{+\infty} \frac{1}{\sqrt{2\pi\sigma^2}}\exp\left(-\frac{(Y_i - \beta t - u_i t)^2}{2\sigma^2}\right)f_{\tau}(u_i,v_i) dv_i du_i \\
                   & + \prod_{i=1}^n \prod_{t=1}^T \int_{u_i=-\infty}^{+\infty}\int_{v_i=-\infty}^{t-\psi} \frac{1}{\sqrt{2\pi\sigma^2}}\exp\left(-\frac{(Y_i - \beta (\psi + v_i) - u_i (\psi + v_i))^2}{2\sigma^2}\right)f_{\tau}(u_i,v_i) dv_i du_i \\
                   =& \frac{1}{(2\pi)^{3nT/2}\sigma^{nT}(\tau_{u,u}\tau_{v,v}-\tau^2_{u,v})^{nT/2}} \prod_{i=1}^n \prod_{t=1}^T \left(\Likelihood_{1,i,t}(\Theta) + \Likelihood_{2,i,t}(\Theta) \right)
\end{align*}
#+END_EXPORT
where we introduce the notation:
#+BEGIN_EXPORT latex
\begin{align*}
\Likelihood_{1,i,t}(\Theta) =& \int_{u_i=-\infty}^{+\infty}\int_{v_i=t-\psi}^{+\infty} \exp\left(-\frac{(Y_i - \beta t - u_i t)^2}{2\sigma^2} - \frac{u_i^2 w_{u,u}+2u_i v_i w_{u,v}+v_i^2 w_{v,v}}{2}\right) dv_i du_i \\
\Likelihood_{2,i,t}(\Theta) =& \int_{u_i=-\infty}^{+\infty}\int_{v_i=-\infty}^{t-\psi} \exp\left(-\frac{(Y_i - \beta (\psi + v_i) - u_i (\psi + v_i))^2}{2\sigma^2} - \frac{u_i^2 w_{u,u}+2u_i v_i w_{u,v}+v_i^2 w_{v,v}}{2}\right) dv_i du_i
\end{align*}
#+END_EXPORT
Using that:
#+BEGIN_EXPORT latex
\begin{align*}
\int_{a}^{b} \exp\left( - \frac{1}{2}(A v_i^2 + 2 B v_i) \right) dv_i 
&= \int_{a}^{b} \exp\left( - \frac{A}{2}(v_i^2 + 2 \frac{B}{A} v_i) \right) dv_i  \\
&= \int_{a}^{b} \exp\left( - \frac{A}{2}(v_i + \frac{B}{A})^2 + \frac{B^2}{2 A} \right) dv_i  \\ 
&= \sqrt{\frac{2 \pi}{A}}\exp\left(\frac{B^2}{2 A}\right)\frac{1}{\sqrt{2 \pi A^{-1}}} \int_{a}^{b} \exp\left( - \frac{(v^2_i- -\frac{B}{A})^2}{2A^{-1}} \right) dv_i \\
&= \sqrt{\frac{2 \pi}{A}}\exp\left(\frac{B^2}{2 A}\right) \left(\Phi_{\mu=-\frac{B}{A},\sigma^2=A^{-1}}(b) - \Phi_{\mu=-\frac{B}{A},\sigma^2=A^{-1}}(a) \right) \\
&= \sqrt{\frac{2 \pi}{A}}\exp\left(\frac{B^2}{2 A}\right) \left(\Phi\left(\frac{bA+B}{\sqrt{A}}\right) - \Phi\left(\frac{aA+B}{\sqrt{A}}\right) \right)
\end{align*}
#+END_EXPORT
where \(\Phi_{\mu,\sigma^2}(\bullet)= \Phi(\frac{\bullet-\mu}{\sigma})\) denotes
the Cumulative Distribution Function (CDF) of a normal distribution
with mean \(\mu\) and variance \(\sigma^2\). For the first term, using
\(a=t-\psi\), \(b=+\infty\), \(A=w_{v,v}\), and \(B = u_i w_{u,v}\),
we obtain:
#+LaTeX: \begin{adjustwidth}{-4em}{-4em}
#+BEGIN_EXPORT latex
\begin{align*}
\Likelihood_{1,i,t}(\Theta) =&
\sqrt{\frac{2\pi}{w_{v,v}}} \int_{-\infty}^{+\infty} \exp\left(-\frac{(Y_i - \beta t - u_i t)^2}{2\sigma^2} - \frac{u_i^2 (w_{u,u} -  \frac{w^2_{u,v}}{w_{v,v}})}{2} \right)
                                             \left(1 - \Phi\left(\frac{w_{v,v} (t-\psi) + u_i w_{u,v}}{\sqrt{w_{v,v}}}\right)\right)du_i
\end{align*}
#+END_EXPORT
#+LaTeX: \end{adjustwidth}
which can be evaluated using numerical intergration
(e.g. =stats::integrate= and =stats::pnorm= - see function next
page). A similar approach can be used to evaluate the second term.
#+LaTeX: \begin{adjustwidth}{-7em}{-7em}
#+BEGIN_EXPORT latex
\begin{align*}
&\Likelihood_{2,i,t}(\Theta) = \int_{u_i=-\infty}^{+\infty}\int_{v_i=-\infty}^{t-\psi} \exp\left(-\frac{(Y_i - \psi (\beta + u_i) - v_i (\beta + u_i))^2}{2\sigma^2} - \frac{u_i^2 w_{u,u}+2u_i v_i w_{u,v}+v_i^2 w_{v,v}}{2}\right) dv_i du_i \\
=& \int_{u_i=-\infty}^{+\infty}\int_{v_i=-\infty}^{t-\psi} \exp\left(-\frac{(Y_i - \psi (\beta + u_i))^2 + v^2_i (\beta + u_i)^2 - 2 v_i (\beta + u_i) (Y_i - \psi (\beta + u_i))}{2\sigma^2} - \frac{u_i^2 w_{u,u}+2u_i v_i w_{u,v}+v_i^2 w_{v,v}}{2}\right) dv_i du_i
\end{align*}
#+END_EXPORT
#+LaTeX: \end{adjustwidth}
Using \(a=-\infty\), \(b=t-\psi\), \(A=w_{v,v}+\frac{(\beta+u_i)^2}{\sigma^2}\), and
\(B = u_i w_{u,v} - h(u_i)\) where
\(h(u_i)=\frac{(\beta+u_i)(Y_i-\psi(\beta+u_i))}{\sigma^2}\), we obtain for \(\Likelihood_{2,i,t}(\Theta)\):

#+LaTeX: \begin{adjustwidth}{-7em}{-7em}
#+BEGIN_EXPORT latex
\begin{align*}
\sqrt{2\pi} \int_{-\infty}^{+\infty} \exp\left(-\frac{(Y_i - \psi (\beta + u_i))^2}{2\sigma^2} - \frac{u_i^2 w_{u,u} -  \frac{(u_i w_{u,v}-h(u_i))^2}{w_{v,v}+\sigma^{-2}(\beta+u_i)^2}}{2} \right)
                                             \frac{\Phi\left( \frac{(w_{v,v}+\sigma^{-2}(\beta+u_i)^2) (t-\psi) + u_i w_{u,v} - h(u_i)}{\sqrt{w_{v,v}+\sigma^{-2}(\beta+u_i)^2}}\right)}{\sqrt{w_{v,v}+\sigma^{-2}(\beta+u_i)^2}} du_i
\end{align*}
#+END_EXPORT
#+LaTeX: \end{adjustwidth}

\clearpage

This approach is (much) more numerically efficient:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
system.time( ## whole dataset 
  resIntegral <- logLik_mixed10(
    Y = df.sim$Y, t = df.sim$X,
    beta = betaT, psi = psiT, sigma2 = sigma2T,
    tau_uu = MtauT[1,1], tau_uv = MtauT[1,2], tau_vv = MtauT[2,2],
    integration  = "univariate")
)
#+END_SRC

#+RESULTS:
:   bruger   system forløbet 
:     0.22     0.00     0.22

#+BEGIN_SRC R :exports both :results output :session *R* :cache no
head(resIntegral)
#+END_SRC

#+RESULTS:
:   integral1       error1    integral2       error2 integral error    logLik
: 1  4.220895 1.368832e-06 1.086702e-88 1.821438e-88 4.220895    NA 1.4400472
: 2  4.810386 1.252909e-03 1.005836e-78 1.705596e-78 4.810386    NA 1.5707774
: 3  2.947875 9.400217e-03 5.921995e-68 9.665419e-68 2.947875    NA 1.0810846
: 4  3.071454 9.777754e-03 1.220746e-61 2.099327e-61 3.071454    NA 1.1221511
: 5  2.468229 1.075678e-02 8.763755e-49 1.579133e-48 2.468229    NA 0.9035010
: 6  2.181034 3.596076e-05 6.274525e-40 1.146041e-39 2.181034    NA 0.7797989


and leads to nearly identical results:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
quantile(resIntegral$logLik[1:NROW(resIntegral2)]-resIntegral2$logLik)
#+END_SRC

#+RESULTS:
:            0%           25%           50%           75%          100% 
: -1.216897e-04 -8.942998e-07  5.361709e-05  2.670979e-04  3.104343e-03

To total log-likelihood can be obtained by summing the =logLik= over
rows:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
sum(resIntegral$logLik)
#+END_SRC

#+RESULTS:
: [1] 59.66285

or, equivalently, setting the argument =indiv= to =FALSE=:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
logLik_mixed10(
  Y = df.sim$Y, t = df.sim$X,
  beta = betaT, psi = psiT, sigma2 = sigma2T,
  tau_uu = MtauT[1,1], tau_uv = MtauT[1,2], tau_vv = MtauT[2,2],
  indiv = FALSE) ## uses univariate-fast by default
#+END_SRC

#+RESULTS:
: [1] 59.66285

** Direct optimisation

\noindent We can now search for the model parameters maximizing the likelihood:
- using a transformation to constrain the breakpoint to be within the
  range of observation times, the variance-covariance matrix of the
  random effect to be positive, and the variance to be positive

#+BEGIN_SRC R :exports both :results output :session *R* :cache no
res.optim <- optim(
  par = c(beta = 1,
          psi.logit = qlogis(0.5),
          tau_uu.log = log(MtauT[1,1]),
          rho_uv = atanh(cov2cor(MtauT)[1,2]),
          tau_vv.log = log(MtauT[2,2]),
          sigma2.log = log(0.05)),
  fn = function(theta){
    theta["psi"] <- max(df.sim$X) * plogis(theta["psi.logit"])
    theta["tau_uu"] <- exp(theta["tau_uu.log"])
    theta["tau_vv"] <- exp(theta["tau_vv.log"])
    theta["tau_uv"] <- sqrt(theta["tau_uu"]*theta["tau_vv"])*tanh(theta["rho_uv"])
    theta["sigma2"] <- exp(theta["sigma2.log"])

    iOut <- try(logLik_mixed10(Y = df.sim$Y, t = df.sim$X,
                               beta = theta["beta"], psi = theta["psi"],
                               tau_uu = theta["tau_uu"],
                               tau_uv = theta["tau_uv"],
                               tau_vv = theta["tau_vv"],
                               sigma2 = theta["sigma2"],
                               indiv = FALSE), silent = TRUE)
    if(inherits(iOut,"try-error")){
      cat("ERROR: ",paste(theta[c("beta","psi","tau_uu","tau_uv","tau_vv","sigma2")], collapse=", "))
      return(Inf) ## optim is minimizing
    }else{
      return(-iOut) ## optim is minimizing
    }
    
  }, control = list(reltol = 1e-3))
#+END_SRC

#+RESULTS:

After back-transformation we obtain the following estimates:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
res.optim$par["psi"] <- max(df.sim$X) * plogis(res.optim$par["psi.logit"])
res.optim$par["tau_uu"] <- exp(res.optim$par["tau_uu.log"])
res.optim$par["tau_vv"] <- exp(res.optim$par["tau_vv.log"])
res.optim$par["tau_uv"] <- sqrt(res.optim$par["tau_uu"]*res.optim$par["tau_vv"])*tanh(res.optim$par["rho_uv"])
res.optim$par["sigma2"] <- exp(res.optim$par["sigma2.log"])
res.optim$par[c("beta","psi","tau_uu","tau_uv","tau_vv","sigma2")]
#+END_SRC

#+RESULTS:
:        beta         psi      tau_uu      tau_uv      tau_vv      sigma2 
: 0.989314425 1.942741606 0.008735823 0.014492654 0.039373193 0.006122932

** Estimating the random effects

Knowing the model parameters and a vector of outcomes for a specific
subject, we can evaluate the subject-specific random effect as the
expected value of the random effect given the observations. We
therefore need the joint distribution of \((Y,u,v)\):
#+BEGIN_EXPORT latex
\begin{align*}
\Esp[Y] =& \beta t + \beta \Esp\left[(t-\psi-v_i)\Ind[t-\psi-v_i>0]\right]  + \Esp\left[u_i(t-\psi-v_i)\Ind[t-\psi-v_i>0]\right] \\
 =& \beta t + \beta (t-\psi) - \Esp\left[v_i\Ind[t-\psi-v_i>0]\right] + (t-\psi)\Esp\left[u_i\Ind[t-\psi-v_i>0]\right] - \Esp\left[u_i v_i\Ind[t-\psi-v_i>0]\right] \\
 =& \beta t + \beta (t-\psi) - \Esp\left[v_i\Ind[v_i < t-\psi]\right] + (t-\psi)\Esp\left[u_i\Ind[v_i<t-\psi]\right] - \Esp\left[u_i v_i\Ind[v_i<t-\psi]\right] 
\end{align*}
#+END_EXPORT

\noindent We now focus on the expectation terms:
#+BEGIN_EXPORT latex
\begin{align*}
\Esp\left[v_i\Ind[v_i < t-\psi]\right]
&= \int_{-\infty}^{t-\psi} \frac{v_i}{\sqrt{2\pi \tau_{v,v}}} \exp\left(-\frac{v_i^2}{2\tau_{v,v}}\right)dv_i \\
&= -\frac{\sqrt{\tau_{v,v}}}{\sqrt{2\pi}}\left[\exp\left(-\frac{v_i^2}{2\tau_{v,v}}\right) \right]_{-\infty}^{t-\psi}
= -\frac{\exp\left(-\frac{(t-\psi)^2}{2\tau_{v,v}}\right) \sqrt{\tau_{v,v}}}{\sqrt{2\pi}} \\
&= \mu_1(t,\psi,\tau_{v,v})
\end{align*}
#+END_EXPORT

#+BEGIN_EXPORT latex
\begin{align*}
&\Esp\left[u_i\Ind[v_i < t-\psi]\right]
= \int_{-\infty}^{+\infty}\int_{-\infty}^{t-\psi} \frac{u_i}{2\pi\sqrt{\tau_{u,u}\tau_{v,v} - \tau^2_{u,v}}} \exp\left(-\frac{w_{v,v} v_i^2+2 w_{u,v} u_i v_i+w_{u,u}  u_i^2}{2}\right)dv_i du_i \\
=& \frac{1}{\sqrt{2\pi w_{v,v}(\tau_{u,u}\tau_{v,v} - \tau^2_{u,v})}} \int_{-\infty}^{+\infty} u_i \exp\left(-\frac{u_i^2 (w_{u,u} - \frac{w^2_{u,v}}{w_{v,v}})}{2}\right)\Phi\left((t-\psi)\sqrt{w_{v,v}}+\frac{w_{u,v}}{\sqrt{w_{v,v}}}u_i\right) du_i \\ 
=& \mu_2(t,\psi,\tau_{u,u},\tau_{u,v},\tau_{v,v})
\end{align*}
#+END_EXPORT

#+BEGIN_EXPORT latex
\begin{align*}
&\Esp\left[u_i v_i\Ind[v_i < t-\psi]\right]
= \int_{-\infty}^{+\infty}\int_{-\infty}^{t-\psi} \frac{u_i v_i}{2\pi\sqrt{\tau_{u,u}\tau_{v,v} - \tau^2_{u,v}}} \exp\left(-\frac{w_{v,v} v_i^2+2 w_{u,v} u_i v_i+w_{u,u}  u_i^2}{2}\right)dv_i du_i 
\end{align*}
#+END_EXPORT



* CONFIG :noexport:
# #+LaTeX_HEADER:\affil{Department of Biostatistics, University of Copenhagen, Copenhagen, Denmark}
#+LANGUAGE:  en
#+LaTeX_CLASS: org-article
#+LaTeX_CLASS_OPTIONS: [12pt]
#+OPTIONS:   title:t author:t toc:nil todo:nil date:nil
#+OPTIONS:   H:3 num:t 
#+OPTIONS:   TeX:t LaTeX:t
#+LATEX_HEADER: %
#+LATEX_HEADER: %%%% specifications %%%%
#+LATEX_HEADER: %
** Latex command
#+LATEX_HEADER: \usepackage{changepage}
#+LATEX_HEADER: \usepackage{ifthen}
#+LATEX_HEADER: \usepackage{xifthen}
#+LATEX_HEADER: \usepackage{xargs}
#+LATEX_HEADER: \usepackage{xspace}
** Notations
** Code
# Documentation at https://org-babel.readthedocs.io/en/latest/header-args/#results
# :tangle (yes/no/filename) extract source code with org-babel-tangle-file, see http://orgmode.org/manual/Extracting-source-code.html 
# :cache (yes/no)
# :eval (yes/no/never)
# :results (value/output/silent/graphics/raw/latex)
# :export (code/results/none/both)
#+PROPERTY: header-args :session *R* :tangle yes :cache no ## extra argument need to be on the same line as :session *R*
# Code display:
#+LATEX_HEADER: \RequirePackage{fancyvrb}
#+LATEX_HEADER: \DefineVerbatimEnvironment{verbatim}{Verbatim}{fontsize=\small,formatcom = {\color[rgb]{0.5,0,0}}}
# ## change font size input
# ## #+ATTR_LATEX: :options basicstyle=\ttfamily\scriptsize
# ## change font size output
# ## \RecustomVerbatimEnvironment{verbatim}{Verbatim}{fontsize=\tiny,formatcom = {\color[rgb]{0.5,0,0}}}
** Display 
#+LATEX_HEADER: \RequirePackage{colortbl} % arrayrulecolor to mix colors
#+LATEX_HEADER: \RequirePackage{setspace} % to modify the space between lines - incompatible with footnote in beamer
#+LaTeX_HEADER:\renewcommand{\baselinestretch}{1.1}
#+LATEX_HEADER:\geometry{top=1cm}
#+LATEX_HEADER: \RequirePackage{colortbl} % arrayrulecolor to mix colors
# ## valid and cross symbols
#+LaTeX_HEADER: \RequirePackage{pifont}
#+LaTeX_HEADER: \RequirePackage{relsize}
#+LaTeX_HEADER: \newcommand{\Cross}{{\raisebox{-0.5ex}%
#+LaTeX_HEADER:		{\relsize{1.5}\ding{56}}}\hspace{1pt} }
#+LaTeX_HEADER: \newcommand{\Valid}{{\raisebox{-0.5ex}%
#+LaTeX_HEADER:		{\relsize{1.5}\ding{52}}}\hspace{1pt} }
#+LaTeX_HEADER: \newcommand{\CrossR}{ \textcolor{red}{\Cross} }
#+LaTeX_HEADER: \newcommand{\ValidV}{ \textcolor{green}{\Valid} }
# ## warning symbol
#+LaTeX_HEADER: \usepackage{stackengine}
#+LaTeX_HEADER: \usepackage{scalerel}
#+LaTeX_HEADER: \newcommand\Warning[1][3ex]{%
#+LaTeX_HEADER:   \renewcommand\stacktype{L}%
#+LaTeX_HEADER:   \scaleto{\stackon[1.3pt]{\color{red}$\triangle$}{\tiny\bfseries !}}{#1}%
#+LaTeX_HEADER:   \xspace
#+LaTeX_HEADER: }
# # change the color of the links
#+LaTeX_HEADER: \hypersetup{
#+LaTeX_HEADER:  citecolor=[rgb]{0,0.5,0},
#+LaTeX_HEADER:  urlcolor=[rgb]{0,0,0.5},
#+LaTeX_HEADER:  linkcolor=[rgb]{0,0,0.5},
#+LaTeX_HEADER: }
** Image
#+LATEX_HEADER: \RequirePackage{epstopdf} % to be able to convert .eps to .pdf image files
#+LATEX_HEADER: \RequirePackage{capt-of} % 
#+LATEX_HEADER: \RequirePackage{caption} % newlines in graphics
#+LATEX_HEADER: \RequirePackage{tikz}
# ## R logo
#+LATEX_HEADER:\definecolor{grayR}{HTML}{8A8990}
#+LATEX_HEADER:\definecolor{grayL}{HTML}{C4C7C9}
#+LATEX_HEADER:\definecolor{blueM}{HTML}{1F63B5}
#+LATEX_HEADER: \newcommand{\Rlogo}[1][0.07]{
#+LATEX_HEADER: \begin{tikzpicture}[scale=#1]
#+LATEX_HEADER: \shade [right color=grayR,left color=grayL,shading angle=60] 
#+LATEX_HEADER: (-3.55,0.3) .. controls (-3.55,1.75) 
#+LATEX_HEADER: and (-1.9,2.7) .. (0,2.7) .. controls (2.05,2.7)  
#+LATEX_HEADER: and (3.5,1.6) .. (3.5,0.3) .. controls (3.5,-1.2) 
#+LATEX_HEADER: and (1.55,-2) .. (0,-2) .. controls (-2.3,-2) 
#+LATEX_HEADER: and (-3.55,-0.75) .. cycle;
#+LATEX_HEADER: 
#+LATEX_HEADER: \fill[white] 
#+LATEX_HEADER: (-2.15,0.2) .. controls (-2.15,1.2) 
#+LATEX_HEADER: and (-0.7,1.8) .. (0.5,1.8) .. controls (2.2,1.8) 
#+LATEX_HEADER: and (3.1,1.2) .. (3.1,0.2) .. controls (3.1,-0.75) 
#+LATEX_HEADER: and (2.4,-1.45) .. (0.5,-1.45) .. controls (-1.1,-1.45) 
#+LATEX_HEADER: and (-2.15,-0.7) .. cycle;
#+LATEX_HEADER: 
#+LATEX_HEADER: \fill[blueM] 
#+LATEX_HEADER: (1.75,1.25) -- (-0.65,1.25) -- (-0.65,-2.75) -- (0.55,-2.75) -- (0.55,-1.15) -- 
#+LATEX_HEADER: (0.95,-1.15)  .. controls (1.15,-1.15) 
#+LATEX_HEADER: and (1.5,-1.9) .. (1.9,-2.75) -- (3.25,-2.75)  .. controls (2.2,-1) 
#+LATEX_HEADER: and (2.5,-1.2) .. (1.8,-0.95) .. controls (2.6,-0.9) 
#+LATEX_HEADER: and (2.85,-0.35) .. (2.85,0.2) .. controls (2.85,0.7) 
#+LATEX_HEADER: and (2.5,1.2) .. cycle;
#+LATEX_HEADER: 
#+LATEX_HEADER: \fill[white]  (1.4,0.4) -- (0.55,0.4) -- (0.55,-0.3) -- (1.4,-0.3).. controls (1.75,-0.3) 
#+LATEX_HEADER: and (1.75,0.4) .. cycle;
#+LATEX_HEADER: 
#+LATEX_HEADER: \end{tikzpicture}
#+LATEX_HEADER: }
** List
#+LATEX_HEADER: \RequirePackage{enumitem} % to be able to convert .eps to .pdf image files
** Color
#+LaTeX_HEADER: \definecolor{light}{rgb}{1, 1, 0.9}
#+LaTeX_HEADER: \definecolor{lightred}{rgb}{1.0, 0.7, 0.7}
#+LaTeX_HEADER: \definecolor{lightblue}{rgb}{0.0, 0.8, 0.8}
#+LaTeX_HEADER: \newcommand{\darkblue}{blue!80!black}
#+LaTeX_HEADER: \newcommand{\darkgreen}{green!50!black}
#+LaTeX_HEADER: \newcommand{\darkred}{red!50!black}
** Box
#+LATEX_HEADER: \usepackage{mdframed}
** Shortcut
#+LATEX_HEADER: \newcommand{\first}{1\textsuperscript{st} }
#+LATEX_HEADER: \newcommand{\second}{2\textsuperscript{nd} }
#+LATEX_HEADER: \newcommand{\third}{3\textsuperscript{rd} }
** Algorithm
#+LATEX_HEADER: \RequirePackage{amsmath}
#+LATEX_HEADER: \RequirePackage{algorithm}
#+LATEX_HEADER: \RequirePackage[noend]{algpseudocode}
** Math
#+LATEX_HEADER: \RequirePackage{dsfont}
#+LATEX_HEADER: \RequirePackage{amsmath,stmaryrd,graphicx}
#+LATEX_HEADER: \RequirePackage{prodint} % product integral symbol (\PRODI)
# ## lemma
# #+LaTeX_HEADER: \RequirePackage{amsthm}
# #+LaTeX_HEADER: \newtheorem{theorem}{Theorem}
# #+LaTeX_HEADER: \newtheorem{lemma}[theorem]{Lemma}
*** Template for shortcut
#+LATEX_HEADER: \newcommand\defOperator[7]{%
#+LATEX_HEADER:	\ifthenelse{\isempty{#2}}{
#+LATEX_HEADER:		\ifthenelse{\isempty{#1}}{#7{#3}#4}{#7{#3}#4 \left#5 #1 \right#6}
#+LATEX_HEADER:	}{
#+LATEX_HEADER:	\ifthenelse{\isempty{#1}}{#7{#3}#4_{#2}}{#7{#3}#4_{#1}\left#5 #2 \right#6}
#+LATEX_HEADER: }
#+LATEX_HEADER: }
#+LATEX_HEADER: \newcommand\defUOperator[5]{%
#+LATEX_HEADER: \ifthenelse{\isempty{#1}}{
#+LATEX_HEADER:		#5\left#3 #2 \right#4
#+LATEX_HEADER: }{
#+LATEX_HEADER:	\ifthenelse{\isempty{#2}}{\underset{#1}{\operatornamewithlimits{#5}}}{
#+LATEX_HEADER:		\underset{#1}{\operatornamewithlimits{#5}}\left#3 #2 \right#4}
#+LATEX_HEADER: }
#+LATEX_HEADER: }
#+LATEX_HEADER: \newcommand{\defBoldVar}[2]{	
#+LATEX_HEADER:	\ifthenelse{\equal{#2}{T}}{\boldsymbol{#1}}{\mathbf{#1}}
#+LATEX_HEADER: }
*** Shortcuts
**** Probability
#+LATEX_HEADER: \newcommandx\Cov[2][1=,2=]{\defOperator{#1}{#2}{C}{ov}{\lbrack}{\rbrack}{\mathbb}}
#+LATEX_HEADER: \newcommandx\Esp[2][1=,2=]{\defOperator{#1}{#2}{E}{}{\lbrack}{\rbrack}{\mathbb}}
#+LATEX_HEADER: \newcommandx\Prob[2][1=,2=]{\defOperator{#1}{#2}{P}{}{\lbrack}{\rbrack}{\mathbb}}
#+LATEX_HEADER: \newcommandx\Qrob[2][1=,2=]{\defOperator{#1}{#2}{Q}{}{\lbrack}{\rbrack}{\mathbb}}
#+LATEX_HEADER: \newcommandx\Var[2][1=,2=]{\defOperator{#1}{#2}{V}{ar}{\lbrack}{\rbrack}{\mathbb}}
#+LATEX_HEADER: \newcommandx\Binom[2][1=,2=]{\defOperator{#1}{#2}{B}{}{(}{)}{\mathcal}}
#+LATEX_HEADER: \newcommandx\Gaus[2][1=,2=]{\defOperator{#1}{#2}{N}{}{(}{)}{\mathcal}}
#+LATEX_HEADER: \newcommandx\Wishart[2][1=,2=]{\defOperator{#1}{#2}{W}{ishart}{(}{)}{\mathcal}}
#+LATEX_HEADER: \newcommandx\Likelihood[2][1=,2=]{\defOperator{#1}{#2}{L}{}{(}{)}{\mathcal}}
#+LATEX_HEADER: \newcommandx\likelihood[2][1=,2=]{\defOperator{#1}{#2}{\ell}{}{(}{)}{}}
#+LATEX_HEADER: \newcommandx\Information[2][1=,2=]{\defOperator{#1}{#2}{I}{}{(}{)}{\mathcal}}
#+LATEX_HEADER: \newcommandx\Score[2][1=,2=]{\defOperator{#1}{#2}{S}{}{(}{)}{\mathcal}}
**** Operators
#+LATEX_HEADER: \newcommandx\Vois[2][1=,2=]{\defOperator{#1}{#2}{V}{}{(}{)}{\mathcal}}
#+LATEX_HEADER: \newcommandx\IF[2][1=,2=]{\defOperator{#1}{#2}{IF}{}{(}{)}{\mathcal}}
#+LATEX_HEADER: \newcommandx\Ind[1][1=]{\defOperator{}{#1}{1}{}{(}{)}{\mathds}}
#+LATEX_HEADER: \newcommandx\Max[2][1=,2=]{\defUOperator{#1}{#2}{(}{)}{min}}
#+LATEX_HEADER: \newcommandx\Min[2][1=,2=]{\defUOperator{#1}{#2}{(}{)}{max}}
#+LATEX_HEADER: \newcommandx\argMax[2][1=,2=]{\defUOperator{#1}{#2}{(}{)}{argmax}}
#+LATEX_HEADER: \newcommandx\argMin[2][1=,2=]{\defUOperator{#1}{#2}{(}{)}{argmin}}
#+LATEX_HEADER: \newcommandx\cvD[2][1=D,2=n \rightarrow \infty]{\xrightarrow[#2]{#1}}
#+LATEX_HEADER: \newcommandx\Hypothesis[2][1=,2=]{
#+LATEX_HEADER:         \ifthenelse{\isempty{#1}}{
#+LATEX_HEADER:         \mathcal{H}
#+LATEX_HEADER:         }{
#+LATEX_HEADER: 	\ifthenelse{\isempty{#2}}{
#+LATEX_HEADER: 		\mathcal{H}_{#1}
#+LATEX_HEADER: 	}{
#+LATEX_HEADER: 	\mathcal{H}^{(#2)}_{#1}
#+LATEX_HEADER:         }
#+LATEX_HEADER:         }
#+LATEX_HEADER: }
#+LATEX_HEADER: \newcommandx\dpartial[4][1=,2=,3=,4=\partial]{
#+LATEX_HEADER: 	\ifthenelse{\isempty{#3}}{
#+LATEX_HEADER: 		\frac{#4 #1}{#4 #2}
#+LATEX_HEADER: 	}{
#+LATEX_HEADER: 	\left.\frac{#4 #1}{#4 #2}\right\rvert_{#3}
#+LATEX_HEADER: }
#+LATEX_HEADER: }
#+LATEX_HEADER: \newcommandx\dTpartial[3][1=,2=,3=]{\dpartial[#1][#2][#3][d]}
#+LATEX_HEADER: \newcommandx\ddpartial[3][1=,2=,3=]{
#+LATEX_HEADER: 	\ifthenelse{\isempty{#3}}{
#+LATEX_HEADER: 		\frac{\partial^{2} #1}{\partial #2^2}
#+LATEX_HEADER: 	}{
#+LATEX_HEADER: 	\frac{\partial^2 #1}{\partial #2\partial #3}
#+LATEX_HEADER: }
#+LATEX_HEADER: } 
**** General math
#+LATEX_HEADER: \newcommand\Real{\mathbb{R}}
#+LATEX_HEADER: \newcommand\Rational{\mathbb{Q}}
#+LATEX_HEADER: \newcommand\Natural{\mathbb{N}}
#+LATEX_HEADER: \newcommand\trans[1]{{#1}^\intercal}%\newcommand\trans[1]{{\vphantom{#1}}^\top{#1}}
#+LATEX_HEADER: \newcommand{\independent}{\mathrel{\text{\scalebox{1.5}{$\perp\mkern-10mu\perp$}}}}
#+LaTeX_HEADER: \newcommand\half{\frac{1}{2}}
#+LaTeX_HEADER: \newcommand\normMax[1]{\left|\left|#1\right|\right|_{max}}
#+LaTeX_HEADER: \newcommand\normTwo[1]{\left|\left|#1\right|\right|_{2}}
#+LaTeX_HEADER: \DeclareMathOperator*{\argmax}{arg\,max}
#+LaTeX_HEADER: \DeclareMathOperator*{\argmin}{arg\,min}
